CREATE DATABASE EvoKanban;
USE EvoKanban;

CREATE TABLE ESTADO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(200)
);
CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(200),
    EMAIL VARCHAR(200),
    CONTRA VARCHAR(200)
);
CREATE TABLE NOTA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(200),
    ID_USUARIO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);
CREATE TABLE TAREA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(200),
    ID_USUARIO INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID)
);
